name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build (Ubuntu)
        run: cargo build --release --verbose
      - name: Upload Ubuntu binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: target/release/crochet

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (macOS)
        run: rustup target add aarch64-apple-darwin
      - name: Build (macOS ARM)
        run: cargo build --release --target aarch64-apple-darwin --verbose
      - name: Upload MacOS binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-binary
          path: target/aarch64-apple-darwin/release/crochet
